apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ingest
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ingest
spec:
  source:
    git:
      url: https://github.com/evankanderson/function-weather-demo.git
      ref:
        branch: main
    subPath: ingest
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
