apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 300Mi
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        cpu: 400m
        memory: 500Mi
