apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: fetch-weather
  namespace: dev
spec:
  broker: default
  filter:
    attributes:
      type: com.example.cityquery
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fetch
