apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: redis-commander
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: ingest
spec:
  image: ghcr.io/joeferner/redis-commander:latest
  env:
  - name: SENTINEL_HOST
    value: rfs-redisfailover
