apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: fetch
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: fetch
spec:
  source:
    git:
      url: https://github.com/evankanderson/function-weather-demo.git
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.fetch
